version: '3.5'

# Note, don't use port 8080 because google oauth uses that

services:
  agent:
    build:
      context: agent
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
  # A document store for memory for the assistant
  # chroma:
  #   image: ghcr.io/chroma-core/chroma:latest
  #   container_name: chroma
  #   volumes:
  #     - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/chroma/index_data:/index_data
  #   environment:
  #     ANONYMIZED_TELEMETRY: False
  #     IS_PERSISTENT: True
  #   ports:
  #     - 6000:8000

  # https://tts.readthedocs.io/en/latest/ - the voice of the assistant
  tts:
    container_name: tts
    # image: ghcr.io/coqui-ai/tts-cpu:latest
    image: synesthesiam/mozillatts:en
    # entrypoint: python3 TTS/server/server.py --model_name tts_models/en/vctk/vits
    ports:
      - "5002:5002"

  # Motorhead for memory for the chat and responses
  # motorhead:
  #   container_name: motorhead
  #   image: ghcr.io/getmetal/motorhead:latest
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - PORT=8001
  #     - REDIS_URL=redis://redis:6379
  #     - MOTORHEAD_LONG_TERM_MEMORY=True
  #     - OPENAI_API_KEY=${MOTORHEAD_API_KEY}
  #     - OPENAI_API_BASE=${MOTORHEAD_API_BASE}
  #   depends_on:
  #     - "redis"
  #   restart: always

  # Backing store for motorhead
#   redis:
#     container_name: redis
#     image: redis/redis-stack:latest
#     restart: always
#     ports:
#       - '6379:6379'
#     volumes: 
#       - redis:/data

# volumes:
#   redis:
#     driver: local
