version: '3.5'

# Note, don't use port 8080 because google oauth uses that

services:
  agent:
    build:
      context: agent
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
  # A document store for memory for the assistant
  # chroma:
  #   image: ghcr.io/chroma-core/chroma:latest
  #   container_name: chroma
  #   volumes:
  #     - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/chroma/index_data:/index_data
  #   environment:
  #     ANONYMIZED_TELEMETRY: False
  #     IS_PERSISTENT: True
  #   ports:
  #     - 6000:8000

  # https://tts.readthedocs.io/en/latest/ - the voice of the assistant
  tts:
    container_name: tts
    # image: ghcr.io/coqui-ai/tts-cpu:latest
    image: synesthesiam/mozillatts:en
    # entrypoint: python3 TTS/server/server.py --model_name tts_models/en/vctk/vits
    ports:
      - "5002:5002"
  memory:
    image: kernelmemory/service
    container_name: memory
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "9001:9001"
    volumes:
      - ./appsettings.Development.json:/app/appsettings.Development.json