name: Agent Build

on:
  push:
    branches:
      - master
    paths:
      - agent/*
  workflow_dispatch:

jobs:
  build_push_installer:
    name: Build and push the installer to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@latest
        
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@latest
        
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@latest

      - name: Log in to Docker Hub
        uses: docker/login-action@latest
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@latest
        with:
          images: silarsis/assistant-agent
          
      - name: Build and push
        uses: docker/build-push-action@latest
        with:
          context: ./agent/
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: silarsis/assistant-agent:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build_push_installer
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@latest
        
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@latest

      - name: Log in to Docker Hub
        uses: docker/login-action@latest
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@latest
        with:
          images: silarsis/assistant-agent
          
      - name: Build and push
        uses: docker/build-push-action@latest
        with:
          context: ./agent/
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: silarsis/assistant-agent:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
